### ISSUE TITLE
Icons Don't show 

### ISSUE THREAD

**Issue by MaximumOv3rdrive** [Mctalian/RPGLootFeed#135]
The icons on the items appear on the gray items but when it applies to any item above that, they have only a colored icon. I sometimes see the icon appear right before it disappears but I believe it is a bug or the fade isn't set correctly for anything above poor quality items. Thanks!

**Comment by MaximumOv3rdrive** [comment]
![WoWScrnShot_092324_212020](https://github.com/user-attachments/assets/f6cb92e1-637e-4316-9558-aa647769dfb2)
![WoWScrnShot_092324_212019](https://github.com/user-attachments/assets/0545c4de-e829-4606-9a6b-1dd5b834eabc)

**Comment by MaximumOv3rdrive** [comment]
This is just with the test mode but it also happens when I am looting generally

**Comment by Mctalian** [comment]
Thanks for the report! I'll take a look. It looks like you're using Masque? If so, which theme are you using? (I'm very new to Masque and only downloaded it to support it in this addon so perhaps I'm applying textures incorrectly 😅 )

If it's intermittent, I have a feeling it could be with caching from the item info calls and I have an idea on how to handle that if that ends up being the case 🤔

**Comment by MaximumOv3rdrive** [comment]
> Thanks for the report! I'll take a look. It looks like you're using Masque? If so, which theme are you using? (I'm very new to Masque and only downloaded it to support it in this addon so perhaps I'm applying textures incorrectly 😅 )
> 
> If it's intermittent, I have a feeling it could be with caching from the item info calls and I have an idea on how to handle that if that ends up being the case 🤔

Cool. I appreciate the response. As for Masque, I am using Masque: Pointy. If you need any assistance, let me know.

**Comment by Mctalian** [comment]
Perfect I'll take a look tonight or tomorrow. I should have more time to dig into issues later this week.

**Comment by MaximumOv3rdrive** [comment]
> Perfect I'll take a look tonight or tomorrow. I should have more time to dig into issues later this week.

I think I figured it out. I did not know that masque was skinning the bar. with it disabled, it appears to be working correctly. I tried to double check everything. No issues. Thanks!

**Comment by Mctalian** [comment]
Hmmm... So the whole row/background of the loot feed item is being textured by Masque and that's what's going on? It should just be the icon/button. I'll still take a look at that Masque theme, but I'm glad you got things working for you! 

Let me know if you notice anything that isn't working right.

**Comment by MaximumOv3rdrive** [comment]
> Hmmm... So the whole row/background of the loot feed item is being textured by Masque and that's what's going on? It should just be the icon/button. I'll still take a look at that Masque theme, but I'm glad you got things working for you!
> 
> Let me know if you notice anything that isn't working right.

It works with masque, just not the pointy icons. for some reason, it keeps a color on to the icon versus fading it. If they are anything but that, it appears to work fine.

**Comment by Mctalian** [comment]
Ok I was looking at Masque: Pointy, and I think that some of the blending and textures are incorrect. In the Masque_Pointy source, I changed the IconBorder.Texture to the `border` path instead of `normal` and I changed Normal.BlendMode to `ADD` and it seemed to be working better.

Judging by the description of that Masque Skin, I think it's heavily focused on buffs and debuffs, so I think if you just choose a different theme in your Masque settings for RPGLootFeed specifically, that would work best. With being so new to Masque, I don't think I can make a reasonable enough suggestion to Pointy.

Sounds like you already got this figured out, but I wanted to share what I found. I'm going to close this out but thanks for bringing this to my attention! I learned some things about Masque skins today 😄
